### ISSUE TITLE
在1.16.2 Paper服务端上出现空指针异常

### ISSUE THREAD

**Issue by Mr-Notch** [SchoolUniform/RealSurvival#8]
```
[Server] [20:12:37 INFO]: [RealSurvival] Enabling RealSurvival v0.4.1
[Server] [20:12:37 INFO]: [RealSurvival]
[Server] [20:12:37 INFO]: [RealSurvival] Load RSEffect: 0
[Server] [20:12:37 INFO]: [RealSurvival] 启用MySQL: false
[Server] [20:12:37 INFO]: [PlaceholderAPI] Successfully registered expansion: rs
[Server] [20:12:37 INFO]: [RealSurvival] Successful loading PlaceholderAPI !
[Server] [20:12:37 INFO]: [RealSurvival] 在world世界中启用RealSurvival
[Server] [20:12:37 INFO]: [RealSurvival] 在world_nether世界中启用RealSurvival
[Server] [20:12:37 INFO]: [RealSurvival] 在world_the_end世界中启用RealSurvival
[Server] [20:12:37 ERROR]: Error occurred while enabling RealSurvival v0.4.1 (Is it up to date?)
[Server] java.lang.NullPointerException: null
[Server] at miskyle.realsurvival.util.watermaker.WaterMakerVer.makeUnknownWater(WaterMakerVer.java:25) ~[?:?]
[Server] at miskyle.realsurvival.data.ConfigManager.registerStatus(ConfigManager.java:113) ~[?:?]
[Server] at miskyle.realsurvival.data.ConfigManager.<init>(ConfigManager.java:90) ~[?:?]
[Server] at miskyle.realsurvival.RealSurvival.onEnable(RealSurvival.java:26) ~[?:?]
[Server] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[Server] [20:12:37 INFO]: [RealSurvival] Disabling RealSurvival v0.4.1
[Server] [20:12:37 ERROR]: Error occurred while disabling RealSurvival v0.4.1 (Is it up to date?)
[Server] java.lang.NullPointerException: null
[Server] at miskyle.realsurvival.data.config.RandomDayConfig.saveAllConfig(RandomDayConfig.java:131) ~[?:?]
[Server] at miskyle.realsurvival.randomday.RandomDayManager.save(RandomDayManager.java:33) ~[?:?]
[Server] at miskyle.realsurvival.RealSurvival.onDisable(RealSurvival.java:39) ~[?:?]
[Server] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-246]
[Server] at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
```
paper构建：246
Minecraft版本：1.16.2
外置 MCDaemonReforged
Java版本：1.8

**Comment by SmileYik** [comment]
您可以尝试关闭服务器后删除randomday.yml并设定好config.yml中的启用世界中的世界名。

**Comment by SmileYik** [comment]
谢谢您的反馈，请等待修复，感谢使用QwQ.

**Comment by SmileYik** [comment]
抱歉久等了,
这个报错原因是因为没有适配1.16.2及以上的nms.
解决方案出来了, 请RealSurvival交流群: 950727559 下载最近上传的.jar文件以压缩包形式打开将"com"文件夹拖入RealSurvival.jar中覆盖就好了, 很抱歉给你带来了不便QwQ
